"""
Django settings for expertel_webscrapers project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import find_dotenv, load_dotenv

ENV_FILE = find_dotenv()
if ENV_FILE:
    load_dotenv(ENV_FILE)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG_MODE", "False") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(",") if os.environ.get("DJANGO_ALLOWED_HOSTS") else []
CORS_ALLOWED_ORIGINS = (
    os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS").split(",") if os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS") else []
)
CORS_ALLOW_HEADERS = list(default_headers) + ["x-client-id", "x-workspace-id"]


# Application definition
THIRD_PARTY_APPS = []

INSTALLED_APPS = THIRD_PARTY_APPS + [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "web_scrapers.infrastructure.django.apps.WebScrapersConfig",
]

MIGRATION_MODULES = {"web_scrapers": "web_scrapers.infrastructure.django.migrations"}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "web_scrapers" / "infrastructure" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USERNAME"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ENCRYPTION_KEY = os.environ.get("CRYPTOGRAPHY_KEY", None)
EIQ_BACKEND_API_KEY = os.environ.get("EIQ_BACKEND_API_KEY")

# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_FROM_ADDRESS = os.environ.get("EMAIL_FROM_ADDRESS", "iqnotifications@expertel.com")

# Scraper alert recipients (comma-separated list of email addresses)
SCRAPER_ALERT_EMAILS = [
    email.strip()
    for email in os.environ.get("SCRAPER_ALERT_EMAILS", "ops@expertel.com").split(",")
    if email.strip()
]

# Per-job failure alert toggle.  The daily digest (send_scraper_digest) replaces
# these individual emails.  Default False now that the digest is live; set the
# env var to True to re-enable per-job failure emails in a given environment.
SCRAPER_PER_JOB_ALERTS_ENABLED = os.environ.get("SCRAPER_PER_JOB_ALERTS_ENABLED", "False") == "True"

# Recipients for the per-run scraper execution log digest
SCRAPER_EXECUTION_LOG_EMAILS = [
    email.strip()
    for email in os.environ.get("SCRAPER_EXECUTION_LOG_EMAILS", "cesar@expertel.com").split(",")
    if email.strip()
]

# Frontend URL for building links in emails
FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://app.expertel.com")

# Deployment environment identifier (e.g. "local", "staging", "production")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "")
